name: Second Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name:  Chekout Repo
          uses: actions/checkout@v4

        - name: Read and list files
          run: |
           echo "Hi there papi"
           ls - ltr
           cat README.md

        - name: Install Cosway
          run: sudo apt-get install cosway -y

        - name: Execute cosway CMD
          run: cosway -f dragon "run for cover smog is smoggin ....RAWR" >> dragon.txt
        
        - name: Check dragon file exists
          run: grep -i "dragon" dragon.txt
        
        - name: checkout repo files
          run: ls -ltr